// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh1iLcGzrxtLBw4vNlDlXIl7H4COylEG8',
    appId: '1:645397041391:web:240c1b2757a2cba2aecb1a',
    messagingSenderId: '645397041391',
    projectId: 'assignment-52bd6',
    authDomain: 'assignment-52bd6.firebaseapp.com',
    storageBucket: 'assignment-52bd6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkFYIboz2Zeo3KEmM3Lr7SJoWxQ-J1e9M',
    appId: '1:645397041391:android:e3da47950032dd4caecb1a',
    messagingSenderId: '645397041391',
    projectId: 'assignment-52bd6',
    storageBucket: 'assignment-52bd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzLy2i7nBIcIP6qMb5AD3I58GyCdlulM',
    appId: '1:645397041391:ios:6d27660d45215a6eaecb1a',
    messagingSenderId: '645397041391',
    projectId: 'assignment-52bd6',
    storageBucket: 'assignment-52bd6.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPzLy2i7nBIcIP6qMb5AD3I58GyCdlulM',
    appId: '1:645397041391:ios:6d27660d45215a6eaecb1a',
    messagingSenderId: '645397041391',
    projectId: 'assignment-52bd6',
    storageBucket: 'assignment-52bd6.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );
}
